server:
  port: 12345
spring:
  datasource:
    name: userdb
    url: jdbc:mysql://localhost:3306/userdb?useUnicode=true?useSSL=true?characterEncoding=utf8
    username: root
    password: 123456
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/static/



